import {
  faBookBible,
  faBookOpenReader,
  faHandshakeSimple,
  faSeedling,
} from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import Head from 'next/head';
import { useRouter } from 'next/router';
import HomeNav from '../components/nav/HomeNav';

export default function Home() {
  const router = useRouter();

  return (
    <div className='min-h-screen pb-8'>
      <Head>
        <title>Morale Swag | Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HomeNav />
      <h1 className='text-center pt-8 text-emerald-200 font-bold text-2xl md:text-4xl mt-4'>
        CHOOSE A SWAG
      </h1>
      <div className='p-8 mt-8 space-y-6 max-w-lg mx-auto'>
        <button
          onClick={() => router.push('/advice')}
          className='shadow-lg flex items-center px-4 space-x-4 bg-emerald-200 w-full py-4 rounded-md'>
          <FontAwesomeIcon
            icon={faHandshakeSimple}
            className='w-10 h-10 text-emerald-700'
          />
          <p className='font-semibold text-lg'>ADVICE</p>
        </button>

        <button
          onClick={() => router.push('/motivational-quotes')}
          className='shadow-lg flex items-center px-4 space-x-4 bg-emerald-200 w-full py-4 rounded-md'>
          <FontAwesomeIcon
            icon={faSeedling}
            className='w-10 h-10 text-emerald-700'
          />
          <p className='font-semibold text-lg truncate'>MOTIVATIONAL QUOTES</p>
        </button>

        <button
          onClick={() => router.push('/proverbs')}
          className='shadow-lg flex items-center px-4 space-x-4 bg-emerald-200 w-full py-4 rounded-md'>
          <FontAwesomeIcon
            icon={faBookOpenReader}
            className='w-10 h-10 text-emerald-700'
          />
          <p className='font-semibold text-lg truncate'>PROVERBS</p>
        </button>

        <button
          onClick={() => router.push('/bible-quotation')}
          className='shadow-lg flex items-center px-4 space-x-4 bg-emerald-200 w-full py-4 rounded-md'>
          <FontAwesomeIcon
            icon={faBookBible}
            className='w-10 h-10 text-emerald-700'
          />
          <p className='font-semibold text-lg truncate'>BIBLE QUOTATIONS</p>
        </button>
      </div>
    </div>
  );
}
